# Generated by Django 5.1.5 on 2025-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_students_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
